#http.host: 0.0.0.0
network.host: 0.0.0.0

bootstrap.memory_lock: true

# Cluster settings
cluster.name: es-cluster
cluster.initial_master_nodes: es01

### x-pack functions
xpack.security.enabled: false
#xpack.graph.enabled: true
xpack.watcher.enabled: false
xpack.monitoring.collection.enabled: true
